from django.contrib import admin

from .models import *
# Register your models here.

admin.site.register(RoomType)
admin.site.register(COA)
admin.site.register(Room)
admin.site.register(Customer)
admin.site.register(Reservation)
admin.site.register(Complain)
admin.site.register(LostAndFound)
admin.site.register(InventoryType)
admin.site.register(Item)
admin.site.register(StockTransaction)
admin.site.register(Damage)
admin.site.register(Laundry)
admin.site.register(Maintenance)
# admin.site.register(Bellboy)
admin.site.register(LuggageStorage)
admin.site.register(FoodType)
admin.site.register(FoodOrder)
admin.site.register(FoodPosOrder)
admin.site.register(ComplimentaryService)
admin.site.register(Bills)
admin.site.register(Consierge)
admin.site.register(CustomerPicture)
admin.site.register(TransactionTable)
admin.site.register(CardNo)
admin.site.register(CostCenter)
admin.site.register(LaundryCost)
admin.site.register(Table)
